# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-11.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/topher/Dropbox/OSU/phd/3DTrim/3DTrim-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/topher/Dropbox/OSU/phd/3DTrim/3DTrim-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-11.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/topher/Dropbox/OSU/phd/3DTrim/3DTrim-master/CMakeFiles /Users/topher/Dropbox/OSU/phd/3DTrim/3DTrim-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/topher/Dropbox/OSU/phd/3DTrim/3DTrim-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mytrim

# Build rule for target.
mytrim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytrim
.PHONY : mytrim

# fast build rule for target.
mytrim/fast:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/build
.PHONY : mytrim/fast

#=============================================================================
# Target rules for targets named mytrim_bub

# Build rule for target.
mytrim_bub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytrim_bub
.PHONY : mytrim_bub

# fast build rule for target.
mytrim_bub/fast:
	$(MAKE) -f CMakeFiles/mytrim_bub.dir/build.make CMakeFiles/mytrim_bub.dir/build
.PHONY : mytrim_bub/fast

#=============================================================================
# Target rules for targets named mytrim_nobub

# Build rule for target.
mytrim_nobub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytrim_nobub
.PHONY : mytrim_nobub

# fast build rule for target.
mytrim_nobub/fast:
	$(MAKE) -f CMakeFiles/mytrim_nobub.dir/build.make CMakeFiles/mytrim_nobub.dir/build
.PHONY : mytrim_nobub/fast

#=============================================================================
# Target rules for targets named mytrim_range

# Build rule for target.
mytrim_range: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytrim_range
.PHONY : mytrim_range

# fast build rule for target.
mytrim_range/fast:
	$(MAKE) -f CMakeFiles/mytrim_range.dir/build.make CMakeFiles/mytrim_range.dir/build
.PHONY : mytrim_range/fast

element.o: element.cc.o
.PHONY : element.o

# target to build an object file
element.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/element.cc.o
.PHONY : element.cc.o

element.i: element.cc.i
.PHONY : element.i

# target to preprocess a source file
element.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/element.cc.i
.PHONY : element.cc.i

element.s: element.cc.s
.PHONY : element.s

# target to generate assembly for a file
element.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/element.cc.s
.PHONY : element.cc.s

invert.o: invert.cc.o
.PHONY : invert.o

# target to build an object file
invert.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/invert.cc.o
.PHONY : invert.cc.o

invert.i: invert.cc.i
.PHONY : invert.i

# target to preprocess a source file
invert.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/invert.cc.i
.PHONY : invert.cc.i

invert.s: invert.cc.s
.PHONY : invert.s

# target to generate assembly for a file
invert.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/invert.cc.s
.PHONY : invert.cc.s

ion.o: ion.cc.o
.PHONY : ion.o

# target to build an object file
ion.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/ion.cc.o
.PHONY : ion.cc.o

ion.i: ion.cc.i
.PHONY : ion.i

# target to preprocess a source file
ion.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/ion.cc.i
.PHONY : ion.cc.i

ion.s: ion.cc.s
.PHONY : ion.s

# target to generate assembly for a file
ion.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/ion.cc.s
.PHONY : ion.cc.s

material.o: material.cc.o
.PHONY : material.o

# target to build an object file
material.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/material.cc.o
.PHONY : material.cc.o

material.i: material.cc.i
.PHONY : material.i

# target to preprocess a source file
material.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/material.cc.i
.PHONY : material.cc.i

material.s: material.cc.s
.PHONY : material.s

# target to generate assembly for a file
material.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/material.cc.s
.PHONY : material.cc.s

mytrim_bub.o: mytrim_bub.cc.o
.PHONY : mytrim_bub.o

# target to build an object file
mytrim_bub.cc.o:
	$(MAKE) -f CMakeFiles/mytrim_bub.dir/build.make CMakeFiles/mytrim_bub.dir/mytrim_bub.cc.o
.PHONY : mytrim_bub.cc.o

mytrim_bub.i: mytrim_bub.cc.i
.PHONY : mytrim_bub.i

# target to preprocess a source file
mytrim_bub.cc.i:
	$(MAKE) -f CMakeFiles/mytrim_bub.dir/build.make CMakeFiles/mytrim_bub.dir/mytrim_bub.cc.i
.PHONY : mytrim_bub.cc.i

mytrim_bub.s: mytrim_bub.cc.s
.PHONY : mytrim_bub.s

# target to generate assembly for a file
mytrim_bub.cc.s:
	$(MAKE) -f CMakeFiles/mytrim_bub.dir/build.make CMakeFiles/mytrim_bub.dir/mytrim_bub.cc.s
.PHONY : mytrim_bub.cc.s

mytrim_nobub.o: mytrim_nobub.cc.o
.PHONY : mytrim_nobub.o

# target to build an object file
mytrim_nobub.cc.o:
	$(MAKE) -f CMakeFiles/mytrim_nobub.dir/build.make CMakeFiles/mytrim_nobub.dir/mytrim_nobub.cc.o
.PHONY : mytrim_nobub.cc.o

mytrim_nobub.i: mytrim_nobub.cc.i
.PHONY : mytrim_nobub.i

# target to preprocess a source file
mytrim_nobub.cc.i:
	$(MAKE) -f CMakeFiles/mytrim_nobub.dir/build.make CMakeFiles/mytrim_nobub.dir/mytrim_nobub.cc.i
.PHONY : mytrim_nobub.cc.i

mytrim_nobub.s: mytrim_nobub.cc.s
.PHONY : mytrim_nobub.s

# target to generate assembly for a file
mytrim_nobub.cc.s:
	$(MAKE) -f CMakeFiles/mytrim_nobub.dir/build.make CMakeFiles/mytrim_nobub.dir/mytrim_nobub.cc.s
.PHONY : mytrim_nobub.cc.s

mytrim_range.o: mytrim_range.cc.o
.PHONY : mytrim_range.o

# target to build an object file
mytrim_range.cc.o:
	$(MAKE) -f CMakeFiles/mytrim_range.dir/build.make CMakeFiles/mytrim_range.dir/mytrim_range.cc.o
.PHONY : mytrim_range.cc.o

mytrim_range.i: mytrim_range.cc.i
.PHONY : mytrim_range.i

# target to preprocess a source file
mytrim_range.cc.i:
	$(MAKE) -f CMakeFiles/mytrim_range.dir/build.make CMakeFiles/mytrim_range.dir/mytrim_range.cc.i
.PHONY : mytrim_range.cc.i

mytrim_range.s: mytrim_range.cc.s
.PHONY : mytrim_range.s

# target to generate assembly for a file
mytrim_range.cc.s:
	$(MAKE) -f CMakeFiles/mytrim_range.dir/build.make CMakeFiles/mytrim_range.dir/mytrim_range.cc.s
.PHONY : mytrim_range.cc.s

sample.o: sample.cc.o
.PHONY : sample.o

# target to build an object file
sample.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample.cc.o
.PHONY : sample.cc.o

sample.i: sample.cc.i
.PHONY : sample.i

# target to preprocess a source file
sample.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample.cc.i
.PHONY : sample.cc.i

sample.s: sample.cc.s
.PHONY : sample.s

# target to generate assembly for a file
sample.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample.cc.s
.PHONY : sample.cc.s

sample_burried_wire.o: sample_burried_wire.cc.o
.PHONY : sample_burried_wire.o

# target to build an object file
sample_burried_wire.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_burried_wire.cc.o
.PHONY : sample_burried_wire.cc.o

sample_burried_wire.i: sample_burried_wire.cc.i
.PHONY : sample_burried_wire.i

# target to preprocess a source file
sample_burried_wire.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_burried_wire.cc.i
.PHONY : sample_burried_wire.cc.i

sample_burried_wire.s: sample_burried_wire.cc.s
.PHONY : sample_burried_wire.s

# target to generate assembly for a file
sample_burried_wire.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_burried_wire.cc.s
.PHONY : sample_burried_wire.cc.s

sample_clusters.o: sample_clusters.cc.o
.PHONY : sample_clusters.o

# target to build an object file
sample_clusters.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_clusters.cc.o
.PHONY : sample_clusters.cc.o

sample_clusters.i: sample_clusters.cc.i
.PHONY : sample_clusters.i

# target to preprocess a source file
sample_clusters.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_clusters.cc.i
.PHONY : sample_clusters.cc.i

sample_clusters.s: sample_clusters.cc.s
.PHONY : sample_clusters.s

# target to generate assembly for a file
sample_clusters.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_clusters.cc.s
.PHONY : sample_clusters.cc.s

sample_dynamic.o: sample_dynamic.cc.o
.PHONY : sample_dynamic.o

# target to build an object file
sample_dynamic.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_dynamic.cc.o
.PHONY : sample_dynamic.cc.o

sample_dynamic.i: sample_dynamic.cc.i
.PHONY : sample_dynamic.i

# target to preprocess a source file
sample_dynamic.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_dynamic.cc.i
.PHONY : sample_dynamic.cc.i

sample_dynamic.s: sample_dynamic.cc.s
.PHONY : sample_dynamic.s

# target to generate assembly for a file
sample_dynamic.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_dynamic.cc.s
.PHONY : sample_dynamic.cc.s

sample_layers.o: sample_layers.cc.o
.PHONY : sample_layers.o

# target to build an object file
sample_layers.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_layers.cc.o
.PHONY : sample_layers.cc.o

sample_layers.i: sample_layers.cc.i
.PHONY : sample_layers.i

# target to preprocess a source file
sample_layers.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_layers.cc.i
.PHONY : sample_layers.cc.i

sample_layers.s: sample_layers.cc.s
.PHONY : sample_layers.s

# target to generate assembly for a file
sample_layers.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_layers.cc.s
.PHONY : sample_layers.cc.s

sample_solid.o: sample_solid.cc.o
.PHONY : sample_solid.o

# target to build an object file
sample_solid.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_solid.cc.o
.PHONY : sample_solid.cc.o

sample_solid.i: sample_solid.cc.i
.PHONY : sample_solid.i

# target to preprocess a source file
sample_solid.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_solid.cc.i
.PHONY : sample_solid.cc.i

sample_solid.s: sample_solid.cc.s
.PHONY : sample_solid.s

# target to generate assembly for a file
sample_solid.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_solid.cc.s
.PHONY : sample_solid.cc.s

sample_wire.o: sample_wire.cc.o
.PHONY : sample_wire.o

# target to build an object file
sample_wire.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_wire.cc.o
.PHONY : sample_wire.cc.o

sample_wire.i: sample_wire.cc.i
.PHONY : sample_wire.i

# target to preprocess a source file
sample_wire.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_wire.cc.i
.PHONY : sample_wire.cc.i

sample_wire.s: sample_wire.cc.s
.PHONY : sample_wire.s

# target to generate assembly for a file
sample_wire.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/sample_wire.cc.s
.PHONY : sample_wire.cc.s

simconf.o: simconf.cc.o
.PHONY : simconf.o

# target to build an object file
simconf.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/simconf.cc.o
.PHONY : simconf.cc.o

simconf.i: simconf.cc.i
.PHONY : simconf.i

# target to preprocess a source file
simconf.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/simconf.cc.i
.PHONY : simconf.cc.i

simconf.s: simconf.cc.s
.PHONY : simconf.s

# target to generate assembly for a file
simconf.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/simconf.cc.s
.PHONY : simconf.cc.s

trim.o: trim.cc.o
.PHONY : trim.o

# target to build an object file
trim.cc.o:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/trim.cc.o
.PHONY : trim.cc.o

trim.i: trim.cc.i
.PHONY : trim.i

# target to preprocess a source file
trim.cc.i:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/trim.cc.i
.PHONY : trim.cc.i

trim.s: trim.cc.s
.PHONY : trim.s

# target to generate assembly for a file
trim.cc.s:
	$(MAKE) -f CMakeFiles/mytrim.dir/build.make CMakeFiles/mytrim.dir/trim.cc.s
.PHONY : trim.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... mytrim"
	@echo "... mytrim_bub"
	@echo "... mytrim_nobub"
	@echo "... mytrim_range"
	@echo "... rebuild_cache"
	@echo "... element.o"
	@echo "... element.i"
	@echo "... element.s"
	@echo "... invert.o"
	@echo "... invert.i"
	@echo "... invert.s"
	@echo "... ion.o"
	@echo "... ion.i"
	@echo "... ion.s"
	@echo "... material.o"
	@echo "... material.i"
	@echo "... material.s"
	@echo "... mytrim_bub.o"
	@echo "... mytrim_bub.i"
	@echo "... mytrim_bub.s"
	@echo "... mytrim_nobub.o"
	@echo "... mytrim_nobub.i"
	@echo "... mytrim_nobub.s"
	@echo "... mytrim_range.o"
	@echo "... mytrim_range.i"
	@echo "... mytrim_range.s"
	@echo "... sample.o"
	@echo "... sample.i"
	@echo "... sample.s"
	@echo "... sample_burried_wire.o"
	@echo "... sample_burried_wire.i"
	@echo "... sample_burried_wire.s"
	@echo "... sample_clusters.o"
	@echo "... sample_clusters.i"
	@echo "... sample_clusters.s"
	@echo "... sample_dynamic.o"
	@echo "... sample_dynamic.i"
	@echo "... sample_dynamic.s"
	@echo "... sample_layers.o"
	@echo "... sample_layers.i"
	@echo "... sample_layers.s"
	@echo "... sample_solid.o"
	@echo "... sample_solid.i"
	@echo "... sample_solid.s"
	@echo "... sample_wire.o"
	@echo "... sample_wire.i"
	@echo "... sample_wire.s"
	@echo "... simconf.o"
	@echo "... simconf.i"
	@echo "... simconf.s"
	@echo "... trim.o"
	@echo "... trim.i"
	@echo "... trim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

